---

- name: Install required packages
  yum:
    name: '{{ item }}'
    state: 'latest'
  with_items: [ 'tzdata','ntp' ]

- name: Configure timezone in /etc/sysconfig/clock
  copy:
    content: 'ZONE="{{ ntp_timezone }}"\n'
    dest: '/etc/sysconfig/clock'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: ntp_timezone is defined and ntp_timezone

- name: Symlink the correct localtime /etc/localtime
  file:
    src: '/usr/share/zoneinfo/{{ ntp_timezone }}'
    dest: '/etc/localtime'
    force: 'yes'
    state: 'link'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: ntp_timezone is defined and ntp_timezone

- name: Configure NTPd
  template:
    src: 'etc/ntpd/ntp.conf.j2'
    dest: '/etc/ntp.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart ntpd' ]

- name: Start the ntp daemon and ensure autostart
  service:
    name: 'ntpd'
    state: 'started'
    enabled: 'yes'
